# .travis.yml
language: node_js
node_js:
  - "7"
  - "6"
script: 'npm run build && npm run citest'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm run setup
dist: trusty
